speak_text:
  description: 让小爱播报指定文本
  fields:
    entity_id:
      description: 实体 ID
      example: "media_player.xiao_ai"
    text:
      description: 要播报的文本
      example: "你好"
execute_text:
  description: 让小爱执行指定指令
  fields:
    entity_id:
      description: 实体 ID
      example: "media_player.xiao_ai"
    text:
      description: 要执行的文本
      example: "播放轻音乐"
    silent:
      description: (可选，默认否)静默执行
      example: "true"
call_action:
  description: 执行 action(供高级用户使用)
  fields:
    siid:
      description: siid
      example: 3
    aiid:
      description: aiid
      example: 1
    inn:
      description: in 参数，列表形式
      example: ""
set_miot_property:
  description: Set property(供高级用户使用)
  fields:
    siid:
      description: siid
      example: 2
    piid:
      description: aiid
      example: 1
    value:
      description: 值
      example: "true"